application: itsobsolete
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: obsolete/ie6.html
  upload: obsolete/ie6.html

- url: /ie6.html
  static_files: obsolete/ie6.html
  upload: obsolete/ie6.html
  
- url: /ie6faq.html
  static_files: obsolete/ie6faq.html
  upload: obsolete/ie6faq.html

- url: /media
  static_dir: media
